/**
    @author Aitor Acedo
    
    Esta clase implementa la interfaz gráfica para el problema del tablero en el que
    se encuentran tres caballos blancos y tres caballos negros.
*/


import java.awt.*;
import java.applet.*;

/**
    La clase pública Applet1 es derivada de Applet y en ella estarán las variables que formarán 
    parte del problema.    
*/

public class Applet1 extends Applet
{
    public int i=1;
    public tablero t=new tablero();
    
    /**
	    El mensaje inc() incrementa un contador que tiene la clase Applet1 para poder
	    realizar las movimientos de los caballos paso a paso.
	*/
    void inc(){
        this.i++;    
    }
    
    /**
        El método init() del appplet es utilizado para inicializar los valores que van a tener
        las variables que se van a representar en el applet justo al abrir éste en el navegador 
        o en el appletviewer.
    */
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		symantec.itools.lang.Context.setApplet(this);
	
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(426,266);
		textField1.setEnabled(false);
		add(textField1);
		textField1.setBounds(72,48,100,40);
		textField2.setEnabled(false);
		add(textField2);
		textField2.setBounds(168,48,100,40);
		textField3.setEnabled(false);
		add(textField3);
		textField3.setBounds(264,48,100,40);
		textField4.setEnabled(false);
		add(textField4);
		textField4.setBounds(72,84,100,40);
		textField5.setEnabled(false);
		add(textField5);
		textField5.setBounds(168,84,100,40);
		textField6.setEnabled(false);
		add(textField6);
		textField6.setBounds(264,84,100,40);
		textField7.setEnabled(false);
		add(textField7);
		textField7.setBounds(72,120,100,40);
		textField8.setEnabled(false);
		add(textField8);
		textField8.setBounds(168,120,100,40);
		textField9.setEnabled(false);
		add(textField9);
		textField9.setBounds(264,120,100,40);
		button1.setLabel("Solucion Paso a Paso");
		add(button1);
		button1.setBackground(java.awt.Color.lightGray);
		button1.setBounds(108,204,132,40);
		button2.setLabel("Inicializar");
		add(button2);
		button2.setBackground(java.awt.Color.lightGray);
		button2.setBounds(276,204,60,40);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		button1.addActionListener(lSymAction);
		button2.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.TextField textField1 = new java.awt.TextField();
	java.awt.TextField textField2 = new java.awt.TextField();
	java.awt.TextField textField3 = new java.awt.TextField();
	java.awt.TextField textField4 = new java.awt.TextField();
	java.awt.TextField textField5 = new java.awt.TextField();
	java.awt.TextField textField6 = new java.awt.TextField();
	java.awt.TextField textField7 = new java.awt.TextField();
	java.awt.TextField textField8 = new java.awt.TextField();
	java.awt.TextField textField9 = new java.awt.TextField();
	java.awt.Button button1 = new java.awt.Button();
	java.awt.Button button2 = new java.awt.Button();
	//}}
	
	
	
	/**
	    Como podremos observar los interfaces gráficaos para cada uno de los problemas
	    se ha realizado sobre la misma estructura, se inicializan las variables del applet
	    para su representación inicial, después se utilizan las clases que contendrá el ploblema 
	    en cuestión y más tarde se implementarán los mñetodos necesarios para que los pasos 
	    del problema queden reflejados en el applet para una mejor comprensión del problema.
	*/    
	
	void inicializa(){
	    textField1.setText("negro");        
	    textField2.setText("negro");        
	    textField3.setText("negro");        
	    textField4.setText("");        
	    textField5.setText("");        
	    textField6.setText("");        
	    textField7.setText("blanco");        
	    textField8.setText("blanco");        
	    textField9.setText("blanco");        
	}
    
    void MuestraTablero2(tablero t){
        textField1.setText(t.tabla[0][0].ficha.tipo);        
	    textField2.setText(t.tabla[0][1].ficha.tipo);        
	    textField3.setText(t.tabla[0][2].ficha.tipo);        
	    textField4.setText(t.tabla[1][0].ficha.tipo);        
	    textField5.setText(t.tabla[1][1].ficha.tipo);        
	    textField6.setText(t.tabla[1][2].ficha.tipo);        
	    textField7.setText(t.tabla[2][0].ficha.tipo);        
	    textField8.setText(t.tabla[2][1].ficha.tipo);        
	    textField9.setText(t.tabla[2][2].ficha.tipo);        
	}
	
	void HacerSolucion(int i){
	       caballo c=new caballo();
	       switch(i){
	            case 1:c.Mov1(t,"blanco",1);
	            break;
	            
	            case 2:c.Mov2(t,"negro",2);
	            break;
	            
	            case 3:c.Mov3(t,"blanco",3);
	            break;
	            
	            case 4:c.Mov4(t,"negro",3);
	            break;
	            
	            case 5:c.Mov5(t,"blanco",2);
	            break;
	            
	            case 6:c.Mov6(t,"negro",1);
	            break;
	            
	            case 7:c.Mov7(t,"blanco",1);
	            break;
	            
	            case 8:c.Mov8(t,"negro",3);
	            break;
	       }
	}
	class SymAction implements java.awt.event.ActionListener
	{         
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button1)
				button1_ActionPerformed(event);
			if (object == button2)
				button2_ActionPerformed(event);
		}
	}

	void button1_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		if(i<9){
		    HacerSolucion(i);
		    inc();
		}    		
		MuestraTablero2(t);
	}

	void button2_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		inicializa();
	}
}
