/*
	A basic extension of the java.applet.Applet class
 */

import java.awt.*;
import java.applet.*;

public class Applet1 extends Applet
{  
    public int i=1;
    public puzzle p=new puzzle();
    public array aux=new array();
    
    public void inc(int i,puzzle p,array aux){
       this.i++;   
    }
    
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		symantec.itools.lang.Context.setApplet(this);
	
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(426,266);
		button1.setLabel("Solucion Paso a Paso");
		add(button1);
		button1.setBackground(java.awt.Color.lightGray);
		button1.setBounds(72,216,156,40);
		button3.setActionCommand("System.out.println(\"Hola\")");
		button3.setLabel("Inicializa");
		add(button3);
		button3.setBackground(java.awt.Color.lightGray);
		button3.setBounds(252,216,96,40);
		textField1.setEnabled(false);
		add(textField1);
		textField1.setBounds(36,24,100,40);
		textField2.setEnabled(false);
		add(textField2);
		textField2.setBounds(168,24,100,40);
		textField3.setEnabled(false);
		add(textField3);
		textField3.setBounds(300,24,100,40);
		textField4.setEnabled(false);
		add(textField4);
		textField4.setBounds(36,84,100,40);
		add(textField5);
		textField5.setBounds(168,84,100,40);
		add(textField6);
		textField6.setBounds(300,84,100,40);
		textField7.setEnabled(false);
		add(textField7);
		textField7.setBounds(36,144,100,40);
		textField8.setEnabled(false);
		add(textField8);
		textField8.setBounds(168,144,100,40);
		textField9.setEnabled(false);
		add(textField9);
		textField9.setBounds(300,144,100,40);
		
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		button1.addActionListener(lSymAction);
		button3.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.Button button1 = new java.awt.Button();
	java.awt.Button button3 = new java.awt.Button();
	java.awt.TextField textField1 = new java.awt.TextField();
	java.awt.TextField textField2 = new java.awt.TextField();
	java.awt.TextField textField3 = new java.awt.TextField();
	java.awt.TextField textField4 = new java.awt.TextField();
	java.awt.TextField textField5 = new java.awt.TextField();
	java.awt.TextField textField6 = new java.awt.TextField();
	java.awt.TextField textField7 = new java.awt.TextField();
	java.awt.TextField textField8 = new java.awt.TextField();
	java.awt.TextField textField9 = new java.awt.TextField();
	//}}
    public void inicializa(){
      textField1.setText("1");     
      textField2.setText("4");     
      textField3.setText("2");     
      textField4.setText("7");     
      textField5.setText("0");     
      textField6.setText("3");     
      textField7.setText("6");     
      textField8.setText("8");     
      textField9.setText("5");
      aux=new array();
      p=new puzzle();
      i=1;
 }
 
 void MostrarTabla2(puzzle p){
        textField1.setText(""+p.tabla[0][0]);
        textField2.setText(""+p.tabla[0][1]);
        textField3.setText(""+p.tabla[0][2]);
        textField4.setText(""+p.tabla[1][0]);
        textField5.setText(""+p.tabla[1][1]);
        textField6.setText(""+p.tabla[1][2]);
        textField7.setText(""+p.tabla[2][0]);
        textField8.setText(""+p.tabla[2][1]);
        textField9.setText(""+p.tabla[2][2]);
 }
 
 void HacerSolucion(int a,puzzle p,array aux){
    switch(a){
        case 1: aux=p.EncuentraVacio();  
                p.MoverArriba(aux.a[0],aux.a[1]);
                break;
        
        case 2: aux=p.EncuentraVacio();  
		        p.MoverDerecha(aux.a[0],aux.a[1]);
                break;
        
        case 3: aux=p.EncuentraVacio();
		        p.MoverAbajo(aux.a[0],aux.a[1]);
                break;
        
        case 4: aux=p.EncuentraVacio();
		        p.MoverIzquierda(aux.a[0],aux.a[1]);
                break;
        
        case 5: aux=p.EncuentraVacio();
		        p.MoverAbajo(aux.a[0],aux.a[1]);
                break;
        
        case 6: aux=p.EncuentraVacio();
		        p.MoverIzquierda(aux.a[0],aux.a[1]);
                break;
        
        case 7: aux=p.EncuentraVacio();
		        p.MoverArriba(aux.a[0],aux.a[1]);
                break;
        
        case 8: aux=p.EncuentraVacio();
		        p.MoverDerecha(aux.a[0],aux.a[1]);
                break;
    }
      
 }
class SymAction implements java.awt.event.ActionListener
{                   
	public void actionPerformed(java.awt.event.ActionEvent event)
	{
		Object object = event.getSource();
		if (object == button1)
			button1_ActionPerformed(event);
		if (object == button3)
			button3_ActionPerformed(event);
	}
}

	void button1_ActionPerformed(java.awt.event.ActionEvent event)
	{	        
		if(i<9){
		    HacerSolucion(i,p,aux);
		    MostrarTabla2(p);
		    inc(i,p,aux);		 		    
		}
	    
	}

	void button3_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		inicializa();	 
	}
}
