/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

char c[20];
  GtkWidget *window3;
  GtkWidget *fixed1;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *button25;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *button28;
  GtkWidget *button29;
  GtkWidget *button30;
  GtkWidget *button31;
  GtkWidget *button32;
  GtkWidget *entry1;

GtkWidget*
create_window3 (void)
{
  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window3), "window3", window3);
  gtk_window_set_title (GTK_WINDOW (window3), "window3");

  fixed1 = gtk_fixed_new ();
  gtk_widget_ref (fixed1);
  gtk_object_set_data_full (GTK_OBJECT (window3), "fixed1", fixed1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window3), fixed1);

  button21 = gtk_button_new_with_label ("S");
  gtk_widget_ref (button21);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button21", button21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed1), button21, 0, 88);
  gtk_widget_set_uposition (button21, 0, 88);
  gtk_widget_set_usize (button21, 40, 120);

  button22 = gtk_button_new_with_label ("0");
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed1), button22, 40, 88);
  gtk_widget_set_uposition (button22, 40, 88);
  gtk_widget_set_usize (button22, 40, 120);

  button23 = gtk_button_new_with_label ("1");
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed1), button23, 80, 88);
  gtk_widget_set_uposition (button23, 80, 88);
  gtk_widget_set_usize (button23, 40, 120);

  button24 = gtk_button_new_with_label ("2");
  gtk_widget_ref (button24);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button24", button24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed1), button24, 120, 88);
  gtk_widget_set_uposition (button24, 120, 88);
  gtk_widget_set_usize (button24, 40, 120);

  button25 = gtk_button_new_with_label ("3");
  gtk_widget_ref (button25);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button25", button25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed1), button25, 160, 88);
  gtk_widget_set_uposition (button25, 160, 88);
  gtk_widget_set_usize (button25, 40, 120);

  button26 = gtk_button_new_with_label ("4");
  gtk_widget_ref (button26);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button26", button26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed1), button26, 200, 88);
  gtk_widget_set_uposition (button26, 200, 88);
  gtk_widget_set_usize (button26, 40, 120);

  button27 = gtk_button_new_with_label ("5");
  gtk_widget_ref (button27);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button27", button27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed1), button27, 240, 88);
  gtk_widget_set_uposition (button27, 240, 88);
  gtk_widget_set_usize (button27, 40, 120);

  button28 = gtk_button_new_with_label ("6");
  gtk_widget_ref (button28);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button28", button28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed1), button28, 280, 88);
  gtk_widget_set_uposition (button28, 280, 88);
  gtk_widget_set_usize (button28, 40, 120);

  button29 = gtk_button_new_with_label ("7");
  gtk_widget_ref (button29);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button29", button29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed1), button29, 320, 88);
  gtk_widget_set_uposition (button29, 320, 88);
  gtk_widget_set_usize (button29, 40, 120);

  button30 = gtk_button_new_with_label ("8");
  gtk_widget_ref (button30);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button30", button30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed1), button30, 360, 88);
  gtk_widget_set_uposition (button30, 360, 88);
  gtk_widget_set_usize (button30, 40, 120);

  button31 = gtk_button_new_with_label ("9");
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed1), button31, 400, 88);
  gtk_widget_set_uposition (button31, 400, 88);
  gtk_widget_set_usize (button31, 40, 120);

  button32 = gtk_button_new_with_label ("N");
  gtk_widget_ref (button32);
  gtk_object_set_data_full (GTK_OBJECT (window3), "button32", button32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed1), button32, 440, 88);
  gtk_widget_set_uposition (button32, 440, 88);
  gtk_widget_set_usize (button32, 40, 120);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (window3), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 0, 0);
  gtk_widget_set_uposition (entry1, 0, 0);
  gtk_widget_set_usize (entry1, 480, 88);

  gtk_signal_connect (GTK_OBJECT (button21), "clicked",
                      GTK_SIGNAL_FUNC (on_button21_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (on_button22_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button23), "clicked",
                      GTK_SIGNAL_FUNC (on_button23_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button24), "clicked",
                      GTK_SIGNAL_FUNC (on_button24_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button25), "clicked",
                      GTK_SIGNAL_FUNC (on_button25_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button26), "clicked",
                      GTK_SIGNAL_FUNC (on_button26_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button27), "clicked",
                      GTK_SIGNAL_FUNC (on_button27_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button28), "clicked",
                      GTK_SIGNAL_FUNC (on_button28_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button29), "clicked",
                      GTK_SIGNAL_FUNC (on_button29_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button30), "clicked",
                      GTK_SIGNAL_FUNC (on_button30_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button31), "clicked",
                      GTK_SIGNAL_FUNC (on_button31_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button32), "clicked",
                      GTK_SIGNAL_FUNC (on_button32_clicked),
                      NULL);

  return window3;
}


void
on_button21_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
gtk_entry_set_text(entry1,"                                   Llamando...");

}


void
on_button22_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"0");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button23_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"1");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button24_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"2");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button25_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"3");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button26_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"4");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button27_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"5");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button28_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"6");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button29_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"7");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button30_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"8");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button31_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
char *c1;
sprintf(c1,"9");
strcat(c,c1);
gtk_entry_set_text(entry1,c);
}


void
on_button32_clicked                    (GtkButton       *button,
                                        gpointer         user_data)
{
sprintf(c,"");
gtk_entry_set_text(entry1,"                                   Colgando...");
}



