#!/bin/bash

# Indentificamos el shell con el que sera interpretado el script que vamos a escribir

#
# Objetivo: tenemos que analizar un fichero log de un servidor ftp y que produzca una serie de estadisticas
# de uso que incluyan:
# 	Numero de accesos por usuario
#	Numero de bytes transferidos
#	Cantidad de maquinas que han usado el acceso ftp 
#


#
# El script tendra que aceptar parametros estos deberan ser:
# 	el subdirectorio
#	USUARIOS
#	BYTES
#	MAQUINAS
#


#
# La estructura del fichero de registro de conexiones FTP sera la siguiente: 
# (Esta es la informacion que contiene el fichero en cada linea)
# 	nombre de la maquina remota
#	tamaño del fichero transferido en bytes
#	nombre del fichero
#	nombre o direccion e-mail (contraseña del FTP anonimo) del usuario que se conectado


if [ $# -lt 2 ]; then
	echo 'Formato: verificaRegistro ruta_directorio [USUARIOS | MAQUINAS | BYTES]...'
else
	param2="/tmp/${1}.dat"
	
	grep /pub/${1} /var/log/ftp.log > $param2
	
	for param in $*; do
		
		case $param in
			USUARIOS) grep /pub/${1} /var/log/ftp.log | cut -d ' ' -f 4 | uniq -c;;
			BYTES)  bytes=`cut -d ' ' -f 2 $param2`
				num2="0"
				for num in $bytes; do
					num2=`expr $num2 + $num`
				done
				echo $num2;;
			MAQUINAS) sort $param2 | uniq -W 1 | wc -l;; 
		esac
	done
	# Borramos el fichero temporal que hemos creado
	rm $param2
fi
