/*
 * Detalles.java
 *
 * Created on 14 de marzo de 2005, 19:40
 */

package Interfaz;

import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.ArrayList;

/**
 *
 * @author  hadden
 */
public class Detalles extends javax.swing.JFrame {
    
    /*Variables de la ventana*/
    String id; //Identifica el pedido
    Integer zona; //Almacena la zona a la que pertenece el pedido en cuestion
    boolean nuevo, modif; //Indica si el pedido es nuevo
    Interfaz.Pedidos parent; //La ventana padre
    
    protected DefaultTableModel m;
    String cols[] = {"producto", "unidades", "precioCompra"};
    Vector vCol;
    
    
    //Numero de columnas
    private final int COLS = 3;
    //Identificadores de columnas
    private final int PRODUCTO = 0;
    private final int UNIDADES = 1;
    private final int PRECIO_COMPRA = 2;
        
    /** Creates new form Detalles */
    public Detalles() {
        parent = null;
        modif = false;
        nuevo = false;
        
        vCol = new Vector();
        
        for(int i=0; i<COLS; i++)
            vCol.addElement(cols[i]);
        
        initComponents();
        
        productos.setEditable(false); //No queremos que el JCombo sea editable
        
        m = (DefaultTableModel)jTable1.getModel();
        
        //deshabilitar();
        
        configurarCombo();
        
        /*Configuracion de la ventana*/
        setSize(545,350);
        setTitle("Visor de detalles");
        setResizable(false);
    }
    
    private void configurarCombo(){
        productos.setEditable(false);
    }
    
    private void deshabilitar(){
        productos.setEnabled(false);
    }
    
    public void visualiza(String i, Integer z, boolean n, Interfaz.Pedidos p){
        Vector v, vp;
        
        nuevo = n;
        
        parent = p; //La ventana padre
        
        /*Buscamos todos los productos que tenemos en el punto de venta*/
        vp = new MantenimientoDB.Productos().buscar("-1");
        
        /*Ponemos las referencias de todos los productos que hemos encontrado en el JCombo*/
        if(vp!=null)
            productos2Combo(vp);
        else
            System.out.println("Se ha producido un error en la busqueda de productos");
        
        //Esta parte se encarga de la tabla
        if(i!=null){
            if(z!=null){
                id = i;
                zona = z;
                v = Pedidos.detalles2Vector(id);
                if(v != null){
                    m.setDataVector(v, vCol); //Reflejamos los cambios en la tabla
                    setVisible(true);
                }else
                    System.out.println("No hay detalles de pedido");
            }else
                System.out.println("No tenemos la zona del pedido");
        }else
            System.out.println("No tenemos id de pedido");
    }
    
    private void productos2Combo(Vector v){
        //Si estamos dentro de este metodo se supone que la ventana ha sido creada
        //y tiene un JCombo inicializado ya!!
        if(v.size()!=0){
            productos.removeAllItems(); //Borramos los posibles productos que hay en el JCombo
            int i=0;
            PuntoDeVenta.PVProductos prod;
            while(i<v.size()){
                prod = (PuntoDeVenta.PVProductos)v.elementAt(i);
                productos.addItem(prod.getRef());
                i++;
            }
        }else
            System.out.println("El numero de productos en el PV es 0");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        productos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        suma = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        suma_unidades = new javax.swing.JButton();
        menos_unidades = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "producto", "unidades", "precioCompra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 30, 280, 210);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        getContentPane().add(aceptar);
        aceptar.setBounds(380, 260, 90, 29);

        getContentPane().add(productos);
        productos.setBounds(360, 60, 170, 27);

        jLabel2.setText("Productos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 40, 70, 16);

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        getContentPane().add(suma);
        suma.setBounds(60, 260, 40, 29);

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        getContentPane().add(menos);
        menos.setBounds(100, 260, 40, 29);

        suma_unidades.setText("+ unidades");
        suma_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_unidadesActionPerformed(evt);
            }
        });

        getContentPane().add(suma_unidades);
        suma_unidades.setBounds(400, 140, 100, 29);

        menos_unidades.setText("- unidades");
        menos_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos_unidadesActionPerformed(evt);
            }
        });

        getContentPane().add(menos_unidades);
        menos_unidades.setBounds(400, 180, 100, 29);

        pack();
    }//GEN-END:initComponents

    private void menos_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos_unidadesActionPerformed
        // TODO TEST
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                Integer u = (Integer)jTable1.getValueAt(row, UNIDADES);
                if(u.intValue()==1){
                    System.out.println("No se puede decrementar mas las unidades!!");
                }else{
                    Double p = (Double)jTable1.getValueAt(row, PRECIO_COMPRA);
                    
                    double pu = p.doubleValue()/u.intValue();
                    pu = p.doubleValue() - pu;
                    
                    /*Cambiamos la tabla*/
                    m.setValueAt(new Double(pu), row, PRECIO_COMPRA);
                    m.setValueAt(new Integer(u.intValue()-1), row, UNIDADES);
                    modif = true;
                }
            }else
                System.out.println("Error en la fila seleccionada");
        }else
            System.out.println("Problema en la configuracion de la ventana");
    }//GEN-LAST:event_menos_unidadesActionPerformed

    private void suma_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_unidadesActionPerformed
        // TODO TEST
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                /*Suponemos que no puede haber ningun problema por como son introducidos*/
                Integer u = (Integer)jTable1.getValueAt(row, UNIDADES);
                Double p = (Double)jTable1.getValueAt(row, PRECIO_COMPRA);
                String ref = ((String)jTable1.getValueAt(row, PRODUCTO)).trim();
                int n = u.intValue()+1;
                double pu = p.doubleValue()/u.intValue();
                pu = pu + p.doubleValue();
                
                /*Cambiamos la tabla*/
                m.setValueAt(new Double(pu), row, PRECIO_COMPRA);
                m.setValueAt(new Integer(n), row, UNIDADES);
                /*Tenemos que cambiar el valor de la lista de detalles para que lo haga bien*/
                parent.modificaDetPed(id, ref, n, pu);
                modif = true;
            }else
                System.out.println("Error en la fila seleccionada");
        }else
            System.out.println("Problema en la configuracion de la ventana");
    }//GEN-LAST:event_suma_unidadesActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO TEST
        /*Hemos hecho codigo redundante*/
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            try{
                int row = jTable1.getSelectedRow();
                if(row != -1){
                    String prod = ((String)jTable1.getValueAt(row, PRODUCTO)).trim();
                    ArrayList l = Pedidos.getDetallesPed(id);
                    if(l.size()>1){
                        Pedidos.eliminaProdDetPed(id, prod);
                        m.removeRow(row);
                        System.out.println("Producto del detalle eliminado");
                        modif = true;
                    }else
                        System.out.println("Producto no se puede eliminar porque solamente hay uno!");
                    
                }else
                    System.out.println("No hay ninguna fila seleccionada");
            }catch(ArrayIndexOutOfBoundsException ai){
                System.out.println("Fila seleccionada no valida");
            }
        }else
            System.out.println("Problema en la configuracion de la ventana");
    }//GEN-LAST:event_menosActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO TEST
        /*Con este boton lo que haremos es coger el producto seleccionado y crear una fila dentro de la tabla con dicho
         producto*/
        /*Tenemos que comprobar que tenemos un producto seleccionado, no se como se hace??*/
        Vector row = new Vector();
        Vector v2;
        //Si funciona igual que para la tabla si no hay nada seleccionado devolver‡ un null
        String ref_prod = (String)productos.getSelectedItem();
        if(ref_prod != null){
            v2 = new MantenimientoDB.Productos().buscar(ref_prod);
            if(v2 != null){
                PuntoDeVenta.PVProductos p;
                p = (PuntoDeVenta.PVProductos)v2.get(0);
                
                Integer uni = new Integer(1);
                Double precio = new Double(p.getPrecio());
                
                row.addElement(ref_prod);
                //Los valores para las otras dos columnas
                row.addElement(uni);
                row.addElement(precio);
                //v.addElement(row);
                m.addRow(row);
                Pedidos.insertaDetalle(id, ref_prod, uni, precio, zona);              
                modif = true;
            }
        }else
            System.out.println("No tenemos nada seleccionado en el JCombo");
    }//GEN-LAST:event_sumaActionPerformed
    
    
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO TEST
        //tendremos que calcular el precio total del pedido con los productos que hemos seleccionado
        setVisible(false);
        if((modif == true)&&(nuevo == false)){
            new MantenimientoDB.Pedidos().modificarDetallePedido(id, Pedidos.getDetallesPed(id));
            parent.calculaPrecioTotal(id);
            modif = false;
        }else if((modif == false)&&(nuevo == true))
            Pedidos.eliminaPedido(id);
        else if((modif == true)&&(nuevo == true)){
            parent.calculaPrecioTotal(id);
            modif = false;
        }
        //Si el pedido no es nuevo y no ha modificado nada no tenemos que hacer nada!
    }//GEN-LAST:event_aceptarActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new Detalles().show();
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menos;
    private javax.swing.JButton menos_unidades;
    private javax.swing.JComboBox productos;
    private javax.swing.JButton suma;
    private javax.swing.JButton suma_unidades;
    // End of variables declaration//GEN-END:variables
    
}
