/*
 * tfnosEmpr.java
 *
 * Created on 10 de marzo de 2005, 18:09
 */

package Interfaz;

import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.ArrayList;

/**
 *
 * @author  hadden
 */
public class tfnosEmpr extends javax.swing.JFrame {
    
    /*Variables de la ventana*/
    String nif; //Sera el nif del empleado al que pertenecen esos telefonos
    boolean modif, nuevo;
    
    protected DefaultTableModel m;
    String cols[] = {"De Empresa"};
    Vector vCol;
    
    /** Creates new form tfnosEmpr */
    public tfnosEmpr() {
        modif = false;
        vCol = new Vector();
        
        vCol.addElement(cols[0]);
        
        initComponents();
        
        m = (DefaultTableModel)jTable1.getModel();
        
        /*Configuracion de la ventana*/
        this.setSize(400,350);
        setResizable(false);
        setTitle("Telefonos Empresa");
    }
    
    private void setNif(String n){
        nif = n;
        //nif = new String(n);
    }
    
    /*El modelo es un VECTOR DE VECTORES cada fila esta representada por un vector!!!!*/
    public void visualiza(String ni, boolean n){
        //TESTED
        Vector v;
        if(ni != null){
            //System.out.println("El nif en tfno: "+ni);
            nuevo = n; //Indica si el empleado es nuevo o no
            setNif(ni);
            v = Empleados.tEmpr2Vector(ni);
            if(v != null){
                //rows = new Vector();
                //rows.addElement(v);
                m.setDataVector(v, vCol); //Reflejamos los cambios en la tabla
                setVisible(true);
            }else
                System.out.println("No hay telefonos");
        }else
            System.out.println("No tengo nif");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ntel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        out = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        getContentPane().add(insertar);
        insertar.setBounds(30, 40, 80, 29);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        getContentPane().add(eliminar);
        eliminar.setBounds(30, 100, 79, 29);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        getContentPane().add(modificar);
        modificar.setBounds(30, 160, 90, 29);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        getContentPane().add(aceptar);
        aceptar.setBounds(290, 230, 80, 29);

        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        getContentPane().add(suma);
        suma.setBounds(170, 230, 40, 29);

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        getContentPane().add(menos);
        menos.setBounds(210, 230, 40, 29);

        jLabel1.setText("Nuevo Telefono:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 120, 16);

        getContentPane().add(ntel);
        ntel.setBounds(28, 220, 110, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "De Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 40, 160, 160);

        getContentPane().add(out);
        out.setBounds(110, 280, 230, 22);

        jLabel2.setText("Estado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 280, 60, 16);

        pack();
    }//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        ArrayList l = Empleados.getTfnoEmpr(nif);
        int i=0;
        setVisible(false);
        out.setText("");
        //Modif indica si se ha realizado alguna operacion sobre los telefonos de un empleado
        if((modif == true)&&(nuevo == false)){ //Si el empleado no es nuevo no modificamos la bd
            /*while(i<l.size()){
                System.out.println("tele: "+l.get(i));
                i++;
            }*/
            //Actualizamos la bd
            new MantenimientoDB.Empleados().modificarTfno(nif, Empleados.getTfnoEmpr(nif),2);
            System.out.println("Telefonos modificados");
            modif = false;
        }else if((modif == false)&&(nuevo == true)){
            Empleados.eliminaEmpTfnoEmpr(nif); //Lo eliminamos de la hash
            System.out.println("Un usuario nuevo no ha modificado su lista de telefonos");
        }else if((modif == true)&&(nuevo == true)){
            modif = false;
            System.out.println("Un usuario nuevo ha modificado su lista de telefonos");
        }
        //Si el empleado no es nuevo y no ha modificado los telefonos NO tenemos que hacer nada!!
    }//GEN-LAST:event_aceptarActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            try{
                m.removeRow(jTable1.getSelectedRow());
            }catch(ArrayIndexOutOfBoundsException ai){
                System.out.println("No hay fila seleccionada");
            }
        }else
            out.setText("Fila no seleccionada");
    }//GEN-LAST:event_menosActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        Vector v = new Vector();
        v.addElement(null);
        m.addRow(v);
    }//GEN-LAST:event_sumaActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        // TODO add your handling code here:
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                String tel;
                //System.out.println("NIF: "+nif);
                try{
                    tel = ((String)jTable1.getValueAt(row, 0)).trim();
                    //System.out.println("tel: "+tel);
                    Empleados.insertaTfnoEmpr(nif, tel);
                    out.setText("Telefono personal insertado");
                    modif = true;                    
                }catch(NullPointerException nu){
                    //System.err.println("Fila sin ningun telefono");
                    out.setText("Fila sin ningun telefono");
                }
                

            }else
                out.setText("Error en la fila seleccionada");
                //System.err.println("Error en la fila seleccionada");
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                String tel;
                try{
                    tel = ((String)jTable1.getValueAt(row, 0)).trim();
                    m.removeRow(row);
                    System.out.println("del tel: "+tel);
                    Empleados.eliminaTfnoEmpr(nif, tel);
                    out.setText("Telefono eliminado");
                    modif = true;
                }catch(NullPointerException nu){
                    out.setText("Fila sin ningun telefono");
                    //System.err.println("Fila sin ningun telefono");
                }
            }else
                out.setText("Error en la fila seleccionada");
                //System.err.println("Error en la fila seleccionada");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        if(!jTable1.getColumnSelectionAllowed() && jTable1.getRowSelectionAllowed()){
            int row = jTable1.getSelectedRow();
            if(row >= 0){
                String tel, tel2;
                try{
                    tel = ((String)jTable1.getValueAt(row, 0)).trim();
                    tel2 = ntel.getText();
                    if(!tel2.equals("")){
                        ntel.setText("");
                        //System.out.println("tfno old: "+tel);
                        //System.out.println("tfno new: "+tel2);
                        Empleados.modificaTfnoEmpr(nif, tel, tel2);
                        m.setValueAt(tel2, row, 0); //Modificamos el contenido de la celda modificada
                        out.setText("Telefono modificado");
                        modif = true;
                    }else
                        out.setText("Error telefono vacio");
                        //System.err.println("Error telefono vacio");
                }catch(NullPointerException nu){
                    out.setText("Fila sin ningun telefono");
                    //System.err.println("Fila sin ningun telefono");
                }
            }else
                out.setText("Error en la fila seleccionada");
                //System.err.println("Error en la fila seleccionada");
        }
    }//GEN-LAST:event_modificarActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new tfnosEmpr().show();
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menos;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField ntel;
    private javax.swing.JTextField out;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
    
}
